services:
  localstack:
    image: localstack/localstack
    detached: true
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    depends_on:
      - mockserver
    links:
      - mockserver
    networks:
      crm-net:
        ipv4_address: "172.16.238.10"

  mockserver:
    image: mockserver/mockserver:5.15.0
    detached: true
    ports:
      - "1080:1080"
    networks:
      crm-net:
        ipv4_address: "172.16.238.20"

networks:
  crm-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
