name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Start LocalStack
        run: |
          pip install --use-pep517 localstack awscli-local  # install LocalStack cli and awslocal
          docker pull localstack/localstack                 # Make sure to pull the latest version of the image
          localstack start -d                               # Start LocalStack in the background
          
          echo "Waiting for LocalStack startup..."          # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                             # to become ready before timing out
          echo "Startup complete"
      - name: Run some Tests against LocalStack
        run: |
          awslocal s3 mb s3://test
          awslocal s3 ls
