name: CI

# Create a local mock AWS and API environment.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  mock:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Start services
        run: docker compose up --detach
        shell: bash
      - name: Create AWS resources
        run: ./scripts/create_aws_resources.sh
        shell: bash
