name: CI

# Create a local mock AWS and API environment.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  mock:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install awslocal
        run: pip install --use-pep517 awscli-local
      - name: Start services
        run: docker compose up
        shell: bash
      - name: Create AWS resources
        run: ./scripts/create_aws_resources.sh
        shell: bash
