name: CI

# Create a local mock AWS and API environment.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  mock-env:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        options: --name localstack
        volumes:
          # - ./init-scripts:/etc/localstack/init/ready.d
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 4566:4566
      mockserver:
        options: --name mockserver
        image: mockserver/mockserver:5.15.0
        ports:
          - 1080:1080
    steps:
      - name: test comms
        run: docker exec localstack curl mockserver:1080
