name: CI

# Create a local mock AWS and API environment.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  mock-env:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      AWS_SECRET_ACCESS_KEY: test
      AWS_ACCESS_KEY_ID: test
      AWS_DEFAULT_REGION: us-east-1
    services:
      localstack:
        image: localstack/localstack:latest
        options: --name localstack
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 4566:4566
      mockserver:
        options: --name mockserver
        image: mockserver/mockserver:5.15.0
        ports:
          - 1080:1080
    steps:
      - name: Create AWS resources in localstack
        run: |
          aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket crm
          aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name crm-fetch
          aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name crm-events
          aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name crm-send
          aws --endpoint-url=http://localhost:4566 dynamodb create-table \
              --table-name crm \
              --attribute-definitions \
                  AttributeName=external_id,AttributeType=S \
                  AttributeName=category,AttributeType=S \
              --key-schema \
                  AttributeName=external_id,KeyType=HASH \
                  AttributeName=category,KeyType=RANGE \
              --billing-mode PAY_PER_REQUEST
      - name: Check if resources were created
        run: |
          aws --endpoint-url=http://localhost:4566 s3api list-buckets
          aws --endpoint-url=http://localhost:4566 sqs list-queues
          aws --endpoint-url=http://localhost:4566 dynamodb list-tables
